import { eq } from "drizzle-orm";
import { db } from "../db/db";
import { notes } from "../db/schema";
import { NoteNotFoundError } from "../exceptions/notes";

export type InputNoteType = {
  title: string;
  body: string;
  isArchived?: boolean;
};

export type ReturnedNoteType = InputNoteType & {
  id: string;
  createdAt: Date;
  updatedAt: Date | null;
};

export async function getNotes(
  filter?: Partial<typeof notes.$inferSelect> & {
    searchString?: string;
    createdAtFrom?: Date;
    createdAtUntil?: Date;
    updatedAtFrom?: Date;
    updatedAtUntil?: Date;
  },
): Promise<ReturnedNoteType[]> {
  // NOTE: This is generated by Gemini AI when doing drizzle migration to newer version
  const whereClause: Record<string, any> = {};

  // If ID is specified, V2 logic bypasses other fields entirely (matching your v1 structure)
  if (filter?.id) {
    whereClause["id"] = { eq: filter.id };
  } else {
    // 1. Title Filter
    if (filter?.title) {
      whereClause["title"] = { ilike: `%${filter.title}%` };
    }

    // 2. Body Filter (Fixed v1 bug targeting notes.title)
    if (filter?.body) {
      whereClause["body"] = { ilike: `%${filter.body}%` };
    }

    // 3. Status Filter
    if (filter?.isArchived !== undefined) {
      whereClause["isArchived"] = { eq: filter.isArchived };
    }

    // 4. CreatedAt Date Range / Match
    if (filter?.createdAt) {
      whereClause["createdAt"] = { eq: filter.createdAt };
    } else if (filter?.createdAtFrom || filter?.createdAtUntil) {
      whereClause["createdAt"] = {};
      if (filter.createdAtFrom)
        whereClause["createdAt"].gte = filter.createdAtFrom;
      if (filter.createdAtUntil)
        whereClause["createdAt"].lte = filter.createdAtUntil;
    }

    // 5. UpdatedAt Date Range / Match
    if (filter?.updatedAt) {
      whereClause["updatedAt"] = { eq: filter.updatedAt };
    } else if (filter?.updatedAtFrom || filter?.updatedAtUntil) {
      whereClause["updatedAt"] = {};
      if (filter.updatedAtFrom)
        whereClause["updatedAt"].gte = filter.updatedAtFrom;
      if (filter.updatedAtUntil)
        whereClause["updatedAt"].lte = filter.updatedAtUntil;
    }

    // 6. Global Search String fallback
    if (!filter?.title && !filter?.body && filter?.searchString) {
      const searchConditions: Record<string, any>[] = [];

      if (!filter.title) {
        searchConditions.push({ title: { ilike: `%${filter.searchString}%` } });
      }
      if (!filter.body) {
        searchConditions.push({ body: { ilike: `%${filter.searchString}%` } });
      }

      if (searchConditions.length > 0) {
        whereClause["OR"] = searchConditions;
      }
    }
  }

  const result = await db.query.notes.findMany({
    where: Object.keys(whereClause).length > 0 ? whereClause : undefined,
  });

  return result;
}

export async function addNote(note: InputNoteType): Promise<ReturnedNoteType> {
  const result = await db
    .insert(notes)
    .values({ ...note })
    .returning();

  return result[0]!;
}

export async function updateNote({
  noteId,
  updatedNoteData,
}: {
  noteId: ReturnedNoteType["id"];
  updatedNoteData: Partial<InputNoteType>;
}): Promise<ReturnedNoteType> {
  const result = await db
    .update(notes)
    .set(updatedNoteData)
    .where(eq(notes.id, noteId))
    .returning();

  if (!result[0]) {
    throw new NoteNotFoundError(noteId);
  }

  return result[0];
}

export async function deleteNote({
  noteId,
}: {
  noteId: ReturnedNoteType["id"];
}): Promise<Pick<ReturnedNoteType, "id" | "title">> {
  const result = await db
    .delete(notes)
    .where(eq(notes.id, noteId))
    .returning({ id: notes.id, title: notes.title });

  if (!result[0]) {
    throw new NoteNotFoundError(noteId);
  }

  return result[0];
}
