/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesGuardRouteImport } from './routes/_notes-guard'
import { Route as NotesGuardIndexRouteImport } from './routes/_notes-guard/index'
import { Route as NotesGuardArchiveRouteImport } from './routes/_notes-guard/archive'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesGuardRoute = NotesGuardRouteImport.update({
  id: '/_notes-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesGuardIndexRoute = NotesGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesGuardRoute,
} as any)
const NotesGuardArchiveRoute = NotesGuardArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => NotesGuardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof NotesGuardIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/archive': typeof NotesGuardArchiveRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/archive': typeof NotesGuardArchiveRoute
  '/': typeof NotesGuardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_notes-guard': typeof NotesGuardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_notes-guard/archive': typeof NotesGuardArchiveRoute
  '/_notes-guard/': typeof NotesGuardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/archive'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/archive' | '/'
  id:
    | '__root__'
    | '/_notes-guard'
    | '/login'
    | '/register'
    | '/_notes-guard/archive'
    | '/_notes-guard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NotesGuardRoute: typeof NotesGuardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notes-guard': {
      id: '/_notes-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NotesGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notes-guard/': {
      id: '/_notes-guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NotesGuardIndexRouteImport
      parentRoute: typeof NotesGuardRoute
    }
    '/_notes-guard/archive': {
      id: '/_notes-guard/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof NotesGuardArchiveRouteImport
      parentRoute: typeof NotesGuardRoute
    }
  }
}

interface NotesGuardRouteChildren {
  NotesGuardArchiveRoute: typeof NotesGuardArchiveRoute
  NotesGuardIndexRoute: typeof NotesGuardIndexRoute
}

const NotesGuardRouteChildren: NotesGuardRouteChildren = {
  NotesGuardArchiveRoute: NotesGuardArchiveRoute,
  NotesGuardIndexRoute: NotesGuardIndexRoute,
}

const NotesGuardRouteWithChildren = NotesGuardRoute._addFileChildren(
  NotesGuardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  NotesGuardRoute: NotesGuardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
