/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesGuardRouteImport } from './routes/_notes-guard'
import { Route as NotesGuardIndexRouteImport } from './routes/_notes-guard/index'

const NotesGuardRoute = NotesGuardRouteImport.update({
  id: '/_notes-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesGuardIndexRoute = NotesGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesGuardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof NotesGuardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof NotesGuardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_notes-guard': typeof NotesGuardRouteWithChildren
  '/_notes-guard/': typeof NotesGuardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_notes-guard' | '/_notes-guard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NotesGuardRoute: typeof NotesGuardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_notes-guard': {
      id: '/_notes-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NotesGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_notes-guard/': {
      id: '/_notes-guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NotesGuardIndexRouteImport
      parentRoute: typeof NotesGuardRoute
    }
  }
}

interface NotesGuardRouteChildren {
  NotesGuardIndexRoute: typeof NotesGuardIndexRoute
}

const NotesGuardRouteChildren: NotesGuardRouteChildren = {
  NotesGuardIndexRoute: NotesGuardIndexRoute,
}

const NotesGuardRouteWithChildren = NotesGuardRoute._addFileChildren(
  NotesGuardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  NotesGuardRoute: NotesGuardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
